//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/MWSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/MWSchema.xsd", IsNullable=false)]
public partial class Root {
    
    private GameType[] gameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Game")]
    public GameType[] Game {
        get {
            return this.gameField;
        }
        set {
            this.gameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/MWSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("Game", Namespace="http://tempuri.org/MWSchema.xsd", IsNullable=false)]
public partial class GameType {
    
    private ItemGroupType[] itemGroupField;
    
    private string nameField;
    
    private string playerField;
    
    private uint countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemGroup")]
    public ItemGroupType[] ItemGroup {
        get {
            return this.itemGroupField;
        }
        set {
            this.itemGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Player {
        get {
            return this.playerField;
        }
        set {
            this.playerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/MWSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("ItemGroup", Namespace="http://tempuri.org/MWSchema.xsd", IsNullable=false)]
public partial class ItemGroupType {
    
    private ItemGroupPartType[] itemGroupPartField;
    
    private GradientType colorGradientField;
    
    private ColorType clearColorField;
    
    private string nameField;
    
    private bool isLocationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemGroupPart")]
    public ItemGroupPartType[] ItemGroupPart {
        get {
            return this.itemGroupPartField;
        }
        set {
            this.itemGroupPartField = value;
        }
    }
    
    /// <remarks/>
    public GradientType ColorGradient {
        get {
            return this.colorGradientField;
        }
        set {
            this.colorGradientField = value;
        }
    }
    
    /// <remarks/>
    public ColorType ClearColor {
        get {
            return this.clearColorField;
        }
        set {
            this.clearColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsLocation {
        get {
            return this.isLocationField;
        }
        set {
            this.isLocationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/MWSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("ItemGroupPart", Namespace="http://tempuri.org/MWSchema.xsd", IsNullable=false)]
public partial class ItemGroupPartType {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/MWSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("ColorGradient", Namespace="http://tempuri.org/MWSchema.xsd", IsNullable=false)]
public partial class GradientType {
    
    private ColorType[] colorField;
    
    private uint gradientStyleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Color")]
    public ColorType[] Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint GradientStyle {
        get {
            return this.gradientStyleField;
        }
        set {
            this.gradientStyleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/MWSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("Color", Namespace="http://tempuri.org/MWSchema.xsd", IsNullable=false)]
public partial class ColorType {
    
    private int redField;
    
    private int greenField;
    
    private int blueField;
    
    private float weightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Red {
        get {
            return this.redField;
        }
        set {
            this.redField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Green {
        get {
            return this.greenField;
        }
        set {
            this.greenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Blue {
        get {
            return this.blueField;
        }
        set {
            this.blueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}
